export enum TemplateEnum {
  ACCOUNT_VERIFICATION = 'ACCOUNT_VERIFICATION.html',
  PASSWORD_RECOVERY = 'PASSWORD_RECOVERY.html',
  WELCOME = 'WELCOME.html',
  MAGIC_LINK_LOGIN = 'MAGIC_LINK_LOGIN.html',
  ONE_TIME_PASSWORD = 'ONE_TIME_PASSWORD.html',
  PAYMENT_SUCCEEDED = 'PAYMENT_SUCCEEDED.html',
}
