FROM node:22.14-bullseye-slim
WORKDIR /home/api/nestjs/saas-and-ecommerce-boilerplate-nestjs

COPY package.json pnpm-lock.yaml ./

RUN npm install -g pnpm
RUN pnpm install --prod --frozen-lockfile

COPY . .

RUN pnpm add @prisma/client@6.4.1
RUN npx prisma generate

RUN pnpm run build
RUN rm -rf src test
RUN pnpm prune --prod

EXPOSE ${PORT_API}

CMD ["sh", "-c", "npx prisma migrate deploy && pnpm run start:prod"]
