FROM node:22.14-bullseye-slim
WORKDIR /home/api/nestjs/saas-and-ecommerce-boilerplate-nestjs

COPY . .

RUN rm -rf node_modules
RUN npm install -g pnpm
RUN pnpm i

RUN pnpm add @prisma/client@6.4.1
RUN npx prisma generate

EXPOSE ${PORT_API}

CMD ["sh", "-c", "npx prisma migrate deploy && pnpm run start:prod"]
