export enum TemplateEnum {
  ACCOUNT_VERIFICATION = 'ACCOUNT_VERIFICATION.html',
  PASSWORD_RECOVERY = 'PASSWORD_RECOVERY.html',
  WELCOME = 'WELCOME.html',
  MAGIC_LINK_LOGIN = 'MAGIC_LINK_LOGIN.html',
}
