global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'nestjs-api'
    metrics_path: /metrics
    static_configs:
      - targets: ['api:3003']

  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector-dev:8889']
