services:
  api:
    container_name: api-dev
    build:
      context: ../..
      dockerfile: docker/files/Dockerfile.dev
    env_file:
      - ../../.env
    depends_on:
      - postgres
      - redis
      - jaeger
    networks:
      - network
    # ports:
    #   - '${MAPPED_PORT_API}:${PORT_API}'
    volumes:
      - ../..:/home/api/nestjs/saas-and-ecommerce-boilerplate-nestjs
    restart: always

  postgres:
    container_name: postgres-dev
    image: postgres:16.3-alpine
    env_file:
      - ../../.env
    networks:
      - network
    ports:
      - '${MAPPED_PORT_DB}:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always

  redis:
    container_name: redis-dev
    image: redis:7.0-alpine
    env_file:
      - ../../.env
    networks:
      - network
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: '512M'
    # ports:
    #   - '${MAPPED_PORT_REDIS}:6379'
    volumes:
      - redis_data:/data
    restart: always
    command: redis-server --loglevel warning

  nginx:
    container_name: nginx-dev
    image: nginx:1.25-alpine
    env_file:
      - ../../.env
    depends_on:
      - api
    networks:
      - network
    ports:
      - '${MAPPED_PORT_NGINX}:80'
    volumes:
      - ../../nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always

  jaeger:
    container_name: jaeger-dev
    image: jaegertracing/all-in-one:1.50
    ports:
      - "${MAPPED_PORT_JAEGER_UI}:16686"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
      - JAEGER_SAMPLER_TYPE=const
      - JAEGER_SAMPLER_PARAM=1
    expose:
      - "14268"
      - "4317"
      - "5778"
    networks:
      - network

networks:
  network:


volumes:
  postgres_data:
  redis_data:
